services:
  frontend:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: "${REACT_APP_API_URL}"
    ports:
      - 3000:3000
      - 9229:9229
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
